### ISSUE TITLE
Please help to locate "parent" functional description of indexes for Microsoft Azure Synapse Spark Analytics

### ISSUE THREAD

**Issue by SynapsePOC** [microsoft/hyperspace#106]
### Describe the issue
It would be very nice if you provide some reference point, where I could learn, how similar or same indexing functionality is provided in Microsoft Azure Synapse Spark Analytics
As per this document: [Hyperspace, an indexing subsystem for Apache Spark™, is now open source](https://cloudblogs.microsoft.com/opensource/2020/06/30/hyperspace-indexing-subsystem-apache-spark-now-open-source/)

**Comment by rapoth** [comment]
Thank you for your question! At the moment, the functionality is the same. Hyperspace in Azure Synapse Analytics has some additional work (mostly optimizations and some catalog integration) that we are working on open-sourcing in the next few weeks. From a performance standpoint, our goal is to port all our optimizations to the open-source Hyperspace.
