### ISSUE TITLE
Store index file names and file sizes in operation log

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#107]
### Describe the issue

Upcoming features require all index files to be present in the index metadata. Also, file sizes of individual files is required. A sample of this could be:
```
{
 ...
 "files": ["root/indexfile1:100MB", "root/indexFile2:1MB"...]
...
}
```
### To Reproduce

Enhancement
### Expected behavior
Index creation / modification adds list of created index files to the operation log along with their file size

### Environment 

na

**Comment by imback82** [comment]
is this similar to #103? cc @pirz

**Comment by apoorvedave1** [comment]
yeah that's right. Only this one also mentions sizes which will be used in optimizations

**Comment by imback82** [comment]
Then, can we merge into one issue so it's easier to track?

**Comment by pirz** [comment]
Yes they are the same, we can go with this one that @apoorvedave1 has created and close #103
