### ISSUE TITLE
Add RefreshIncrementalAction class to support index creation on newly appended data 

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#110]
### Describe the issue

Implement incremental indexing support for append-only data. Implementation outline:
- identify newly added data files
- create new index version on these files
- update metadata to reflect the latest snapshot of index to include old files and new files

New Api: `refresh(mode = quick)`
### To Reproduce
na

### Expected behavior
na

### Environment 
na

**Comment by sezruby** [comment]
I think `file size` and `modification time` for each file are also required to ensure that the files are not modified. Currently we identify this with the signature value, but supporting append data (+ hybrid scan) needs to check if the existing index can cover the subset of dataset or not.
