### ISSUE TITLE
Capture source file info to detect the change of the dataset

### ISSUE THREAD

**Issue by sezruby** [microsoft/hyperspace#120]
**Describe the problem**

As we are extending the features like dataset with append or delete, it's required to detect the change of the source files to figure out which files are appended or deleted. This could be done only with the list of file paths, but we need additional information to check the integrity of the dataset. We can calculate a new signature only with the files in the captured file paths, but it's hard to detect accidently modified files without size or timestamp. 
Although Hyperspace assumes that user won't tamper the dataset, we should avoid using the invalid index data.

- For append-only dataset without delete, the modified file (same file name, different size or timestamp)
  - query time
    - will invalidate the whole indexes as the current (immutable dataset) does
  - refresh time
    - should force full rebuild
  - these can be done with the current signature value (only with paths)
- For append-only dataset with delete, the modified file
  - query time
    - will invalidate the whole indexes as the current (immutable dataset) does
  - refresh time
    - Option1) should be considered as "deleted" file and also handled as newly "appended" file
    - Option2) or full rebuild?
  - option 1 **requires to identify which file is modified by using captured timestamp and size**
- For hybrid scan, the modified file
  - query time
    - considered as "deleted" file and also "appended" file
  - this also requires to identify which file is modified 

**Describe your proposed solution**
As FilebaseSignatureProvider is using file name + size + modification time, we could capture size and modification time additionally.

```
// Current
case class Content(root: String, directories: Seq[Content.Directory])                       
object Content {                                                                            
  case class Directory(path: String, files: Seq[String], fingerprint: NoOpFingerprint)      
}                                                                                           

// Suggested
case class File(path: String, size: Int, timestamp: Timestamp) // or timestamp: String
case class Content(root: String, directories: Seq[Content.Directory])                       
object Content {                                                                            
  case class Directory(path: String, files: Seq[File], fingerprint: NoOpFingerprint)      
}    
```

Then we could compare the captured values to identify each file is modified or not.

**Describe alternatives you've considered**

**Additional context**

**Comment by sezruby** [comment]
@pirz please review this because dataset w/ delete might require this feature. Thanks!

**Comment by pirz** [comment]
This looks good to me, I am just assuming the file path is really the file name and the full path to a file is the `directory path + file name`. Does that make sense?

**Comment by sezruby** [comment]
That makes sense, but with `directory path`, file path can still include sub directory e.g `directory path` + `/a/b/fileName.parquet`. And the current ver. doesn't capture "path" of the source directory, but "rootPaths". 

For this validation purpose, I think we don't need to factor out the directories for the source file paths. The structure of source directories might be more complex than index data directories. Do you have any other reason or purpose to require the structured directories of source files?

cc: @imback82 

@apoorvedave1 Would you cover these additional metadata of source files with your PR1? or not? Either way, we could use the new File class and functions for #107.

**Comment by imback82** [comment]
> Do you have any other reason or purpose to require the structured directories of source files?

I think this is just one way of saving the metadata file size, and shouldn't affect the correctness.

**Comment by apoorvedave1** [comment]
thanks @sezruby , I have added the changes to the pr #122 suggested in this issue.
