### ISSUE TITLE
Remove deleted records during refresh

### ISSUE THREAD

**Issue by pirz** [microsoft/hyperspace#133]
### Describe the issue
Add support for below scenario:

1. User creates an index on top of some data. The data can be partitioned or non-partitioned.
2. User removes some files and/or full partitions of data. (This makes the index unusable as it no longer captures the latest status of source data).
3. User calls `refreshIndex` API to fix the index and brings it back to active usable state. 

During index refresh, add support for detecting and removing index records which were originally generated from data records that are now deleted.

Pre-requisite: Add lineage to index records (Issue #104) 

### To Reproduce
N/A

### Expected behavior
Scenario described above should work correctly.

### Environment 
All.

**Comment by apoorvedave1** [comment]
#142 fixes this
