### ISSUE TITLE
[FEATURE REQUEST]: Enhancement of Index statistics

### ISSUE THREAD

**Issue by sezruby** [microsoft/hyperspace#146]
### Describe the issue

It would be good to have more detailed statistics about available indexes. This can be done by
- create new APIs such as 
  - `hs.getIndexStat()` for all indexes and `hs.getIndexStat(index)` for an index
- extend IndexSummary class (hs.indexes)
  - IndexSummary (current)
    - Index name
    - indexed columns
    - included columns
    - number of buckets
    - index schema json
    - index location
    - index state
  - candidate properties
    - Total index data size including all versions (disk)
    - latest version info
      - index build time (creation or refresh)
      - index data size
      - index bucket number
    - number of versions
    - number of index data files (increased by incremental refresh) for optimizeIndex

We can provide additional information about source relations of an index to give users some insights so that they could refresh the invalidated index or turn on hybrid scan config. To detect delta of source relations, an input DataFrame is required. So API might look like `hs.getAvailableIndexes(df)` which shows both valid and invalidated indexes for the given DataFrame (or plan). For invalidated indexes, additional properties might be:
- Number of appended files
- Total size of appended data
- Number of deleted file
- Total size of deleted data

**Comment by rapoth** [comment]
@imback82 Could you open a related feature to list the data source location when users utilize `indexes.show` API?
