### ISSUE TITLE
[FEATURE REQUEST]: Introduce a similarity threshold for Hybrid Scan

### ISSUE THREAD

**Issue by sezruby** [microsoft/hyperspace#159]
**Feature requested**

As a developer, I want to introduce some similarity threshold about dataset for hybrid scan in order to avoid performance regression.

Currently, Hybrid scan considers an index as a candidate if an input relation includes one or more same source files of the index. However, in case the "diff" dataset is much larger than the common dataset, shuffling overhead for the "diff" dataset might outweigh the benefit from the index.

In order to avoid the regression by doing Hybrid scan, we could introduce some threshold so that the indexes which covers less amount data of the given relation would not be considered as a candidate index.

The threshold might be
- the number of common files; only works for append-only dataset
- the total size of common files

And we could adjust the threshold - "N % of similarity " - with a new Hyperspace config and set a proper default value based on some experimental results.

**Acceptance criteria** 

- [x] The threshold should be configurable by `HyperspaceConf`.
- [x] The default value should be determined based on experimental results using large dataset.
- [x] Calculating threshold should be finished in reasonable time.

**Success criteria**

- [ ] Calculating threshold overhead.
- [ ] The experimental result for the default value.

**Additional context**

It would be good to print some log why hybrid scan is not applied.

**Comment by rapoth** [comment]
Out of curiosity, in case of issues like this, does it make sense to provide `To Reproduce` and `Expected behavior`?

**Comment by sezruby** [comment]
I think this is more like "User story" in JIRA, not bug or issue report. As this project does not have JIRA-like thing, it would be good to have a new template(and tag) here for relatively small features or tasks for tacking development.

**Comment by rapoth** [comment]
Good point. I created a [new template for feature request](https://github.com/microsoft/hyperspace/issues/new?assignees=&labels=untriaged%2C+enhancement&template=feature-request-template.md&title=%5BFEATURE+REQUEST%5D%3A+). If you agree, can you change this issue to follow that template?

**Comment by sezruby** [comment]
Thanks @rapoth :) I updated the document.
