### ISSUE TITLE
Hyperspace.explain / df.explain doesn't work as expected

### ISSUE THREAD

**Issue by imback82** [microsoft/hyperspace#16]
**Describe the issue**
`Hypersapce.explain` / `df.explain` doesn't pick up the filter index as expected.

**To Reproduce**
```Scala
  import spark.implicits._
  Seq((1, "name1"), (2, "name2")).toDF("id", "name").write.mode("overwrite").parquet("table")
  val df = spark.read.parquet("table")

  val hs = new Hyperspace(spark)

  hs.createIndex(df, IndexConfig("index", indexedColumns = Seq("id"), includedColumns = Seq("name")))
  hs.indexes.show

  val query = df.filter(df("id") === 1).select("id", "name")
  hs.explain(query, verbose = true) // doesn't pick up "index"

  // Now utilize the indexes.
  spark.enableHyperspace
  query.explain // doesn't pick up "index"
  query.show // DOES pick up "index"
```
Looks like if the project is the same as filter output, `Project` seems to be removed when the rule runs, thus `FilterIndexRule` cannot match. `show()` seems to work fine.

The following also works fine: `val query = df.filter(df("id") === 1).select("id")`

**Expected behavior**
It should pick up the index in `Hyperspace.explain` or `df.explain` to avoid confusion.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Tested with Apache Spark 2.4.6 / Hyperspace 0.1.0.

**Additional context**
N/A

**Comment by rapoth** [comment]
Resolved as part of #73
