### ISSUE TITLE
Add index metadata update in RefreshIndex for quick mode

### ISSUE THREAD

**Issue by pirz** [microsoft/hyperspace#169]
### Describe the issue
This issue tracks the work for adding index metadata update action in RefreshIndex quick mode.
Index metadata update action is invoked by user thru calling RefreshIndex API with `mode = "quick"`.
Index metadata update, modifies `IndexLogEntry` by:

1. Collecting list of appended and deleted source data files from last version of index and updating `appendedFiles` and `deletedFiles` lists under source content.
2. Updating list of source data files. (Related: Issue #198)
3. Updating index signature according to latest source data files.

This is needed as part of:

- Add support for deletes in RefreshIndex for quick mode. (issue #134)  
- Add support for appends in RefreshIndex for quick mode

### To Reproduce
1. User creates an index on some data.
2. User deletes some data files or partitions from source data files used in step (1) and appends some new data files.
3. User should be able to refresh the index metadata by updating index's source content and its signature according to the status of latest source data file from step (2). 

### Environment 
All.

**Comment by sezruby** [comment]
Closed by mistake and #238 will close this issue.
