### ISSUE TITLE
HyperSpace bucketing doubt

### ISSUE THREAD

**Issue by mayurdb** [microsoft/hyperspace#180]
Hi, I could not find the mailing list so asking the doubt I have here. 

Based on my understanding, HyperSpace will remove the Exchange and a Sort if it finds a corresponding index. But while doing a write to bucketed table, spark will write multiple files per bucket (so potentially there can be n (number of buckets) x p (number of partitions) files). So even though each of the file within the bucket is sorted, bucket as a whole need not be sorted.

So if this is the case and we remove the sort as well, would that not lead to incorrect results?

I haven't yet reproduced this, I will try to do that if needed.

**Comment by imback82** [comment]
@mayurdb Hyperspace currently writes one file per bucket when you create an index, so `Sort` will be removed. There is an ongoing work that could introduce multiple files per bucket (e.g., incremental refresh), but in this case, `Sort` will _not_ be removed.

**Comment by mayurdb** [comment]
Oh okay. Can you please point me to the code where we add an exchange and a sort to ensure single sorted file per bucket or this happens as part of the code below internally?

`    def saveWithBuckets(
        df: DataFrame,
        path: String,
        numBuckets: Int,
        bucketByColNames: Seq[String]): Unit = {
      require(numBuckets > 0, "The number of buckets must be a positive integer.")

      runCommand(df.sparkSession) {
        DataSource(
          sparkSession = df.sparkSession,
          className = "parquet",
          // In the current implementation of Hyperspace indexes, we have made sure that
          // the "bucketBy" and "sortBy" columns are the same.
          bucketSpec = Some(BucketSpec(numBuckets, bucketByColNames, bucketByColNames)),
          options = HashMap("path" -> path))
          .planForWriting(SaveMode.Overwrite, df.queryExecution.analyzed)
      }
    }`

**Comment by imback82** [comment]
I am a bit confused by your question. Are  you interested in where `Exchange` / `Sort` is added? You can check https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/exchange/EnsureRequirements.scala and https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/DataSourceScanExec.scala#L273

**Comment by mayurdb** [comment]
My bad I should have been more detailed.

In `org.apache.spark.sql.execution.datasources.FileFormatWriter#write`, one file will be written per partition (assuming each partition has at least one row belonging to each bucket). There might be a gap in my understanding here, so please do point out if that's not the case.

So I was thinking if HyperSpace is ensuring one file per bucket, it must be adding an explicit shuffle (using hash partitioner) and a sort before writing the data.

**Comment by imback82** [comment]
Oh, you are referring to the write path, sorry I misunderstood you question. You can check here: https://github.com/microsoft/hyperspace/blob/master/src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala#L131

Basically if you do `repartition` followed by `bucketBy` with the same number of partitions, Spark will ensure that you will have one file per bucket. Note that we don't call `bucketBy` directly since it only works with writing to the catalog table.

**Comment by rapoth** [comment]
@mayurdb I am going to close this but feel free to re-open if you have more questions. 

@pirz Could you please add this to our FAQs?
