### ISSUE TITLE
More unit tests required for checking "appended" and "deleted" files in index metadata

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#195]
### Describe the issue

After PR #191 goes in, the index metadata will contain "deletedFiles" and "appendedFiles". Add unit tests for these scenarios:

Test 1:
1. Source data, create index.
2. delete some files. Update METADATA ONLY (maybe through refreshIndex(mode = "quick") to update "deletedFiles"
2. delete some more files. This time do not update the metadata.
3. call "refreshIndex(mode = "incremental")
4. Assert
    1. All deleted files were used up in refresh
    2. `deletedFiles` in metadata is cleared
    3. `appendedFiles` in metadata is updated, if there were any appended files.

Test 2:
1. Source data, create index.
2. Append some files. Update METADATA ONLY (maybe through refreshIndex(mode = "quick") to update "appendedFiles"
2. Append some more files. This time do not update the metadata.
3. call "refreshIndex(mode = "incremental")
4. Assert
    1. All appended files were used up in refresh
    2. `deletedFiles` in metadata is updated, if there were any deleted files.
    3. `appendedFiles` in metadata is cleared.

**Comment by rapoth** [comment]
@apoorvedave1 I'm closing this since it is not needed after the merge of RefreshAppend and RefreshDelete. Feel free to re-open if you think otherwise.
