### ISSUE TITLE
Numeric id-based lineage column

### ISSUE THREAD

**Issue by sezruby** [microsoft/hyperspace#200]
**Feature requested**

Currently, the lineage column in index data contains the full path of each source file, in String type.
This is an initial approach for the lineage column to support "delete" dataset.

There are some disadvantages for this approach:
- storage bloat
- high memory footprint when reading the index data
- high comparison cost - string comparison

though,
- easy to maintain
- can apply partition filter (not implemented yet)

We can optimize the lineage column by assigning a unique id to each source file.

The following metadata change is required and need to keep the last unique id for newly appended source files.
```
// cur
case class FileInfo(name: String, size: Long, modifiedTime: Long)

// suggested
case class FileInfo(name: String, size: Long, modifiedTime: Long, id: Long)
```

With this, the lineage column can be defined with the "id" value/Long type instead of the full path / String type.

**Acceptance criteria** 

Should work well with the current features using the lineage column:
- [ ] incremental refresh
- [ ] HybridScan

**Success criteria**

**Additional context**

**Comment by rapoth** [comment]
@sezruby Thanks for writing this up! Can you also put up the success criteria? Also, how can we still support partitioning? (maybe use ids instead of actual partition keys for push-down?)

**Comment by pirz** [comment]
Added by #234
