### ISSUE TITLE
Update the Python binding for new refresh and optimize APIs

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#203]
Can you or @thrajput also update the Python binding?

@AFFogarty can help on the C# side once 0.3 is released. (I will ping you @AFFogarty 😄 when it's ready)

_Originally posted by @imback82 in https://github.com/microsoft/hyperspace/pull/187#issuecomment-706868422_

**Comment by imback82** [comment]
We need Python binding for optimize as well: #166
