### ISSUE TITLE
appendedFiles / deletedFiles in IndexLogEntry can be stored as Seq[FileInfo] instead of Seq[String]

### ISSUE THREAD

**Issue by imback82** [microsoft/hyperspace#210]
> `RefreshDeleteAction` handles the modified files as deleted files, and also as appended files.

Does it make sense to update `appendedFiles` / `deletedFiles` to be `Seq[FileInfo]` in index log entry for completeness (esp. if someone is reading the index log entry)?

_Originally posted by @imback82 in https://github.com/microsoft/hyperspace/pull/207#issuecomment-707868254_

**Comment by pirz** [comment]
@sezruby This is needed for #200 - If you have not started it probably I should take it. Plz let me know.

**Comment by sezruby** [comment]
@priz Thanks for letting me know! This is also required for #198, so I was working on this with it. I've pushed #228 for this issue.

**Comment by pirz** [comment]
> @priz Thanks for letting me know! This is also required for #198, so I was working on this with it. I've pushed #228 for this issue.

Thank you @sezruby
