### ISSUE TITLE
Add an API to determine if an index is invalid (i.e., if base table changed).

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#22]
**Describe the issue**

Add an API like `hs.isValid(indexName)` which returns true or false depending on whether the index is valid.
An Index can become invalid if the original data is changed. This would lead to signature mismatch and index would become unusable.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Comment by rapoth** [comment]
We should subsume this as part of the new Why Not? API. @sezruby Can you please include this use case in your proposal?
