### ISSUE TITLE
Investigate whether OR condition can use bucketing info for Join optimization.

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#23]
**Describe the issue**
Investigate whether `OR` condition can use bucketing info for Join optimization.
Hyperspace currently supports conditions like `select C, D from T1, T2 where T1.A = T2.A AND T1.B = T2.B` where this condition in CNF form can be optimized with indexes. Investigation required to test whether `select C, D from T1, T2 where T1.A = T2.A OR T1.B = T2.B` can also be optimized.

**To Reproduce**
Not supported yet
**Expected behavior**
NA
**Screenshots**
NA
**Desktop (please complete the following information):**
NA
**Additional context**
NA

**Comment by imback82** [comment]
`OR` would create `CartesianProduct`, so we don't need to handle this case, right?

**Comment by apoorvedave1** [comment]
I think we can close this issue since we are not supporting it, and bucketing doesn't support it either.
