### ISSUE TITLE
[FEATURE REQUEST]: Update notebooks to showcase hybrid scan scenarios for all languages

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#246]
### Describe the issue

Currently Hitchhiker's docs on hyperspace only showcase basic usages of index maintenance and usage apis. It doesn't include an example of hybrid scan with append and delete scenarios. We need to add e2e examples of hybrid scan on all three languages.

**Comment by apoorvedave1** [comment]
@sezruby could you please take this up if you have bandwidth?

**Comment by sezruby** [comment]
@imback82 @pirz @apoorvedave1 How about exposing `FileUtils` for python and C#? 
It seems there's no proper way w/o using external library.
