### ISSUE TITLE
Gold Standard for query plan check

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#261]
### Describe the issue

Gold Standard for query plan check.

**Comment by imback82** [comment]
@apoorvedave1 Will this be a benchmarking framework or framework to check the plan similar to https://github.com/apache/spark/blob/master/sql/core/src/test/scala/org/apache/spark/sql/PlanStabilitySuite.scala?

**Comment by rapoth** [comment]
Closing in favor of #334
