### ISSUE TITLE
[PROPOSAL]: Obtain Enhanced Index Statistics

### ISSUE THREAD

**Issue by pirz** [microsoft/hyperspace#275]
## Goal
This design proposal is for implementing enhancement #146

We want to make it possible for a user to get some detailed statistics on existing Hyperspace indexes. These statistics summarize some important logical/physical properties of index and they can be useful for different scenarios on the user side s.a. deciding about triggering index optimization.

## Current Situation
Currently, the only way for a user to get some information and statistics about existing indexes is by checking the output of `Hyperspace.indexes` API. This output lists below information for each index:
1. Index name
2. Indexed columns
3. Included columns
4. Number of buckets
5. Index schema
6. Index state

## Proposed Changes
We propose to make two changes:
1. Introduce `getIndexStat()` API: This is a new API in Hyperspace that is invoked by user to obtain information and statistics on an index.
2. Extend the set of information and statistics that are already shown for indexes by adding more/richer details.

**Note.** This change does not add/modify existing index metadata. Those new statistics that are not explicitly captured in index metadata get computed and added to the output of `getIndexStat()`, as the API is invoked.

### `getIndexStat` API
This new API is defined as:

```
def getIndexStat(indexName: String): DataFrame
```

Once user invokes `getIndexStat` API for a given index, Hyperspace uses the "latest stable"  index metadata to collect and compute required stats. 

Note that no concurrency control happens as this command is running (i.e. It does not lock the index in a "transitioning" state according to Hyperspace concurrency model). As a result, if index gets changed during this time, those changes may or may not be included in the command output, depending on when they are added to the latest stable index metadata log.

### Additional Index Information & Statistics
In addition to info/stats that are already available to user (listed above), we include below items to the output of `getIndexStat`:

1. Index kind
2. Number/Size of index files (latest version)
3. Number/Size of source data files (latest version)
4. Lineage enabled
5. Number of index versions
6. Number/Size of appended files
7. Number/Size of deleted files
8. Index root paths for active versions

### Comments
**c1.** One stat that could be added is "index build time". A couple of points about it:
1. For a fresh index, which is an index that is created and has not been refreshed, "build time" is well-defined. It can be estimated using the difference between timestamps in index metadata logs of "creating" and "active" states. However, once the index goes thru one or more refresh cycles, it is not clear how the build time should be defined, as the index content is gradually/incrementally changed.
2. While reporting "build time" seems interesting, a major problem with it is its accuracy:
   - Build time is highly dependent on the the job specification and available resources when the index creation Spark job was running. In addition, potential failed executors or tasks could affect it significantly.
   - It is not clear what type of practical user scenario can benefit from it. It can not be used as a time estimate for a full refresh, as refresh in the full mode is suggested for an index which has gone thru significant source data changes and such changes affects the accuracy of an old build time (i.e. if refreshed in the full mode, index is going to be created on a pretty much different content now).
3. Finally, unlike most of other metrics, "build time" is a fairly straightforward metric to measure on the client side. It is also explicitly available in Spark history server logs that capture index creation job. Therefore, user can easily obtain it, if it is really needed.

**c2.** Another interesting stat to report is "index usage count": "How many times an index has been used in user(s) workload(s), over time?". A couple of points:
1. This metric needs proper definition. What does an "index usage" mean? Should we consider each and every time an index is picked by a Hyperspace rule as a hit count? Do we consider all queries or some of them? What if the query fails? What if some other optimization overrides an index leverage? These are some questions that should be precisely answered to define/add "index usage" as a reported metric.
2. All the info/stats that are included in `getIndexStat` output can be obtained directly from index metadata logs. The log gets updated each and every time a change happens in index that could affect any of these stats. However, "index usage count" is not captured in the index metadata and can not be computed from physical artifacts of an index (i.e. metadata logs, or index files). Updating index metadata during query optimization is not practical either, due to its expensive overhead. More discussion is needed on how such a "score" should be traced for an index, once "index usage" is defined precisely.

**Comment by sezruby** [comment]
`extended = true` option seems unnecessary now. How about showing the total size under index director, not calculating only index data size of all versions?
And I think it would be good not to use Dataframe to show the results like indexes.show - it prints only a small part of the result strings. WDYT? @pirz

**Comment by pirz** [comment]
@sezruby 
> How about showing the total size under index director, not calculating only index data size of all versions?

Do you mean "Total size of index files (latest version)" which is already included in `extended = false` output?

>  it would be good not to use Dataframe to show the results

Using DF is a good option as it is an easy/standard way to make the output usable for consumer code for further filter/extend and using it for different purposes. That is why we decided `indexes` API output to be DF, in the first place.
Regarding "printing a small portion" concern, that happens due to the default truncation that Spark does on the output of `show`. You can force showing whole value for each DF field by setting truncate argument to false: i.e. by calling `df.show(false)`.

**Comment by sezruby** [comment]
> Do you mean "Total size of index files (latest version)" which is already included in extended = false output?

Yes let's add `extended` mode later if it's necessary. I think it's for long results like all rootPaths of source / print all source file paths. 

> Using DF is a good option 

Ok then using DF is fine. Thanks for letting me know about `indexes.show(false)`.

How about add involved? versions for the latest index version which are linked by incremental refresh? 
So that users can remove unused index versions.

**Comment by pirz** [comment]
> How about add involved? versions for the latest index version which are linked by incremental refresh?

@sezruby - Can you plz explain above comment? Do you mean exploring index files and extract how many top-level version directories are involved? If yes, I am not sure what is the best way to capture/show them in the final DF. Probably a short example from you can help here.

**Comment by sezruby** [comment]
Yes, specifically root paths of index content data. For example 
ColumnName: "IndexDataRootPaths"
Value: `path/to/indexName/v__=0`, `path/to/indexName/v__=1`

**Comment by pirz** [comment]
Closed with #286
