### ISSUE TITLE
Hybrid Scans: Use indexes of partially indexed data, and use original data for unindexed data

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#30]
### Describe the issue
Currently if new additional data gets added to the old data, the indexes on the older part of data become obsolete. Hyperspace doesn't use this stale index at all. Investigate and find if some form of "Hybrid" scanning could be done to utilize the partially created indexes if possible and if it improves performance.

### To Reproduce
NA
### Expected behavior
If new data is added, indexes from the older data are still usable along with additional work done for the newly arrived data
### Environment 
NA

**Comment by sezruby** [comment]
Sorry I didn't know this issue already exists. Let's duplicate this with #150 and work with it. Thanks!

**Comment by rapoth** [comment]
Good catch! I will close this issue since it is a duplicate (@apoorvedave1 - Please feel free to reopen if you disagree). Thank you!
