### ISSUE TITLE
Remove Test duplication, e.g. creation of test object IndexLogEntry is highly duplicated

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#31]
### Describe the issue
Remove Test duplication, e.g. creation of test object IndexLogEntry is highly duplicated. This is required only for code cleanup. No functionality change.

### To Reproduce
NA

### Expected behavior
NA

### Environment 
NA

**Comment by clee704** [comment]
Is it still open?

**Comment by sezruby** [comment]
Closed by #77 & #89
