### ISSUE TITLE
[PROPOSAL]: Support Iceberg table format

### ISSUE THREAD

**Issue by andrei-ionescu** [microsoft/hyperspace#318]
## Problem description

This design proposal is for adding feature request #306.

Currently, Hyperspace supports creating indexes only simple formats (like parquet, etc.) and Delta, but not Iceberg. 

As [Iceberg table format](https://iceberg.apache.org) is close to Delta it would be very useful to have Iceberg support in Hyperspace.

## Goal

The user should be able to do use the current API to create an index over an Iceberg dataset and use it in queries.

## Proposed solution

Using the same Hyperspace APIs indexes over Iceberg datasets should work in the same way as for the other implementations.

Given the `icebergDataset` Iceberg dataset with schema

```
root
 |-- id: long (nullable = false)
 |-- str: string (nullable = true)
 |-- date: timestamp (nullable = true)
```

This is the way and index on `str` field with other 2 projection fields can be created

```
hs.createIndex(
  icebergDataset, 
  IndexConfig(
    "index_ice_str",
    indexedColumns = Seq("str"),
    includedColumns = Seq("date", "id")
  )
)
```

Adding the support for Iceberg into Hyperspace has many aspects and I'll try to explain each of these aspects.

### DataSourceV2 support

Iceberg is built on top of the Spark DataSourceV2 API thus Hyperspace should be able to work with these kind of sources and alter the plans containing the `DataSourceV2Relation` types. `DataSourceV2Relation` gives us access to the `IcebergSource` and although the access to its properties is limited we can use it and together with Iceberg table API we can get the latest version of the table and the linked files.

On the same note the Hyperspace rules will need also to be able to work with `DataSourceV2Relation` and alter the plan as needed.

For example, given a query like this

```
val query = icebergDataset.filter(icebergDataset("str") === "f81qj").select("date", "str", "id")
hs.explain(query, true)
```

The rules should be able to transform the plan like bellow:

```
=============================================================
Plan with indexes:
=============================================================
Project [date#3419, str#3418, id#3417L]
+- Filter (isnotnull(str#3418) && (str#3418 = f81qj))
   <----+- FileScan parquet [str#3418,date#3419,id#3417L] Batched: true, DataFilters: [isnotnull(str#3418), (str#3418 = f81qj)], Format: Parquet, Location: InMemoryFileIndex[.../indexes/index_perf_10M/v__=0/part-00000-tid-967265036..., PartitionFilters: [], PushedFilters: [IsNotNull(str), EqualTo(str,f81qj)], ReadSchema: struct<str:string,date:timestamp,id:bigint>---->

=============================================================
Plan without indexes:
=============================================================
Project [date#3419, str#3418, id#3417L]
+- Filter (isnotnull(str#3418) && (str#3418 = f81qj))
   <----+- ScanV2 iceberg[id#3417L, str#3418, date#3419] (Filters: [isnotnull(str#3418), (str#3418 = f81qj)], Options: [path=.../iceberg/table_perf_10M,paths=[]])---->

=============================================================
Indexes used:
=============================================================
index_perf_10M:.../indexes/index_perf_10M/v__=0

=============================================================
Physical operator stats:
=============================================================
+-----------------+-------------------+------------------+----------+
|Physical Operator|Hyperspace Disabled|Hyperspace Enabled|Difference|
+-----------------+-------------------+------------------+----------+
|*DataSourceV2Scan|                  1|                 0|        -1|
|    *Scan parquet|                  0|                 1|         1|
|           Filter|                  1|                 1|         0|
|          Project|                  1|                 1|         0|
|WholeStageCodegen|                  1|                 1|         0|
+-----------------+-------------------+------------------+----------+
```

### Add functionality to detect if the index is up to date

This functionality will let users know wether the index is on sync with the data. This can be achieved either by checking the logged files against the dataset files.

Another way of doing this is by checking the table's latest snapshot id and the latest used for indexing if that is stored and available.

### API changes

Switch from `LogicalRelation` parameter type to `LogicalPlan`.

```
def createRelation(nodeRelation: LogicalPlan, fileIdTracker: FileIdTracker): Option[Relation]

def signature(nodeRelation: LogicalPlan): Option[String]

def allFiles(nodeRelation: LogicalPlan): Option[Seq[FileStatus]]

def partitionBasePath(nodeRelation: LogicalPlan): Option[String]

def lineagePairs(nodeRelation: LogicalPlan, fileIdTracker: FileIdTracker): Option[Seq[(String, Long)]]

def hasParquetAsSourceFormat(nodeRelation: LogicalPlan): Option[Boolean]
```

### Code sections that will be affected

* `actions/CreateAction*`
* `actions/Refresh*Action*`
* `rules/*`
* `sources/*`
* `FileBaseSignatureProvider`
* `utils`

## Impact

There should be no impact on the current Hyperspace implementations.

**Comment by imback82** [comment]
> We need to have support for Iceberg specific `IndexLogEntry` and support for managing it. This may lead to adding an Iceberg specific `IndexLogManager` but that will be decided at the implementation time.

I am a bit concerned with "Iceberg specific `IndexLogEntry`" and "Iceberg specific `IndexLogManager`"? Could you elaborate on this? We shouldn't have a specific implementation of `IndexLogManager` for a source type.

> Switch from `LogicalRelation` parameter type to `LeafNode`.

This is fine, but let's just use `LogicalPlan` as a parameter to be future-proof.

Other than above comments, the proposal seems reasonable to me.

**Comment by andrei-ionescu** [comment]
I totally agree to use the `LogicalPlan` instead on `LeafNode`.

Now, getting back to the first concern: _"Iceberg specific IndexLogEntry"_.

From the beginning I want to say that I may not fully understand the inner workings of Hyperspace and I may be wrong with this "Iceberg specific IndexLogEntry" proposal. Modifying the code and testing it will make it clearer.

I thought that this change may be needed to have the incremental refresh working with Iceberg but again I may be wrong. 

I'll remove it for now and if that is necessary I'll create another proposal for incremental refresh.

**Comment by imback82** [comment]
Ah OK. We can tackle the incremental refresh as a separate proposal/PR. You can check #301 as a reference.

**Comment by andrei-ionescu** [comment]
I may be able to make the incremental refresh with the current means &#8212; tracking files &#8212; but it may be less efficient.

To make it specific to Iceberg and more efficient I will probably open later a separate proposal/PR.

**Comment by imback82** [comment]
OK. I suggest opening a PR first for updating the source provider API since there are places where `LogicalRelation` and `HadoopFsRelation` are matched directly in `RuleUtils.scala`.
