### ISSUE TITLE
Remove test dependency on IndexLogManager.getLatestLog() and mark it as final.

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#32]
### Describe the issue
Code Cleanup: 
Remove test   dependency on IndexLogManager.getLatestLog() and mark it as final.
Currently tests extend IndexLogManager class and override some methods of this class like getLatestLog. Improve this design so that source classes (e.g. IndexLogManager) should not depend on tests to keep their behavior.
### To Reproduce
NA
### Expected behavior
NA
### Environment 
NA

**Comment by saucam** [comment]
Is this still relevant? I could not find any test class extending IndexLogManager

**Comment by imback82** [comment]
This is the place: https://github.com/microsoft/hyperspace/blob/7f235ca5d1ab3f088ae901431eac4d736c27ed2f/src/test/scala/com/microsoft/hyperspace/index/IndexCollectionManagerTest.scala#L38

**Comment by clee704** [comment]
Seems you can simply remove the override, because the default implementation will work just fine
