### ISSUE TITLE
[FEATURE REQUEST]: Include the Hyperspace version in the index metadata

### ISSUE THREAD

**Issue by imback82** [microsoft/hyperspace#345]
**Feature requested**

It would be helpful if we include the Hyperspace version in the index metadata to better support backward compatibility. Currently, it's very hard to see which version of Hyperspace was used when indexes were created.

**Comment by thugsatbay** [comment]
I can take a look at this.

**Comment by imback82** [comment]
One thing to remember is that the version should be read from [version.sbt](https://github.com/microsoft/hyperspace/blob/master/version.sbt).

Maybe https://github.com/sbt/sbt-buildinfo can help? (I haven't tried it though)

**Comment by imback82** [comment]
@sezruby let's include the PR # (or link it) when you close an issue.

**Comment by clee704** [comment]
I think it's #364 and #367.
