### ISSUE TITLE
[FEATURE REQUEST]: Improve source provider API by introducing SourceRelationMetadata

### ISSUE THREAD

**Issue by imback82** [microsoft/hyperspace#360]
Currently, `FileBasedSourceProvider` can return `FileBasedRelation` given a `LogicalPlan`, where `FileBasedRelation` can implement source-specific APIs such as `signature`, `allFiles`, etc.

Similarly, we should update `FileBasedSourceProvider` to return `FileBasedRelationMetadata` (which extends `SourceRelationMetadata`) based on a given `Relation` metadata, and move `refreshRelationMetadata` and `internalFileFormatName` out of the provider.

Now, the `FileBasedSourceProvider` will just act as a factory and provides only the following APIs:
```scala
// existing
def isSupportedRelation(plan: LogicalPlan): Option[Boolean]
def getRelation(plan: LogicalPlan): Option[FileBasedRelation]

// new
def isSupportedRelationMetadata(metadata: Relation): Option[Boolean]
def getRelationMetadata(metadata: Relation): Option[FileBasedRelationMetadata]
```

And new traits would be:
```scala
trait SourceRelationMetadata
trait FileBasedMetadata extends SourceRelationMetdata {
  // Implementation of the provider's `refreshRelationMetadata`
  def refresh(relation: Relation): Relation
  // Implementation of the provider's `internalFileFormatName`
  def internalFileFormatName: String
}
```

**Comment by imback82** [comment]
I will get to this when #272 and #358 are merged.

**Comment by imback82** [comment]
@clee704 do you want to work on this?

**Comment by clee704** [comment]
I'll take this
