### ISSUE TITLE
Scala style does NOT allow 2021 Copyright

### ISSUE THREAD

**Issue by andrei-ionescu** [microsoft/hyperspace#382]
We are now in 2021. Scala style check (`sbt clean compile`) should allow this:

```
Copyright (2021) The Hyperspace Project Authors.
...
```

Instead it fails with: 

```
[error] /Users/aionescu/github/hyperspace/src/main/scala/com/microsoft/hyperspace/index/rules/PlanUtils.scala: Header does not match expected text
```

**Comment by andrei-ionescu** [comment]
@imback82 Can you have a look at this issue?

**Comment by imback82** [comment]
Yea, we can update https://github.com/microsoft/hyperspace/blob/master/scalastyle-config.xml to support different years, but not sure if it's necessary: https://softwareengineering.stackexchange.com/questions/130478/what-copyright-date-for-an-update-to-an-open-source-project-from-last-year 

But, I am not an expert on this and @rapoth should know better.

**Comment by andrei-ionescu** [comment]
I'm not expert either. 

From [Wikipedia / Copyright notice](https://en.wikipedia.org/wiki/Copyright_notice): 

> Use of the notice informs the public that a work is protected by copyright, identifies the copyright owner, and shows the year of first publication.

What I know, and the way I do understand it is that the "publication" means the file. 

In the case of a new file with code I would say that it would have to be the year when the file was created. In the case of updates to already existing file the year should remain untouched.

**Comment by clee704** [comment]
Regardless of whether it's necessary or not, the current rule seems too strict. Let me take this.
