### ISSUE TITLE
Hyperspace not using Index which I created

### ISSUE THREAD

**Issue by ashishchoksi** [microsoft/hyperspace#409]
I have created an index on one Dataframe, not on another. 
I am performing a join operation on two data frames on the index column where one has an index and another doesn't have.

while using API "explain" I haven't seen the index on the physical plan though I have created an index on one data frame.  

Does Hyperspace only use an index if both data frames have on the particular column? or Is there any other setting which I need to change?

Also sometimes I noticed even if for both data frames, I have created an index and use that column for join It is using an index for inner join but not for outer join. why is that?

**Comment by clee704** [comment]
It seems Hyperspace uses indexes for joins only if both children have them. However I couldn't find whether it only supports inner joins or not. Currently it only supports equijoins or joins with a conjunction of equality functions (A = B AND C = D ...).

**Comment by rapoth** [comment]
@ashishchoksi Could you provide a code snippet that explains the scenario?

**Comment by ashishchoksi** [comment]
closing this out.
deleting the index and recreating works for me.
