### ISSUE TITLE
[FEATURE REQUEST]: Update azure-pipelines.yml to build on Windows

### ISSUE THREAD

**Issue by imback82** [microsoft/hyperspace#469]
**Feature requested**

Update azure-pipelines.yml to add building on Windows.

**Success criteria**

CI will build/test on Windows as well.

**Comment by imback82** [comment]
I have a PR open for this (#376), but it needs to be updated. Anyone can pick this up if interested (just leave a comment in #376 that you will be working on it).

**Comment by paryoja** [comment]
I've made PR for this issue. #470  Please review it.

**Comment by imback82** [comment]
Thanks @paryoja!
