### ISSUE TITLE
Deduplicate getIndexesForPlan() and findCoveringIndexes() functions which are duplicated in FilterIndexRule and JoinIndexRule

### ISSUE THREAD

**Issue by pirz** [microsoft/hyperspace#51]
### Describe the issue
`FilterIndexRule.findCoveringIndexes()` function and `JoinIndexRule.getIndexesForPlan()` function are similar in  implementation.
Refactor them as common code in a single function and change the classes to use that.

### To Reproduce
NA

### Expected behavior
FilterIndex rule and JoinIndex rule implementation under [rules](https://github.com/microsoft/hyperspace/tree/master/src/main/scala/com/microsoft/hyperspace/index/rules) should not have duplicate code for finding covering indexes.

### Environment 
NA

**Comment by rapoth** [comment]
CC: sezruby
