### ISSUE TITLE
Replace printStackTrace with Logging in IndexLogManager class

### ISSUE THREAD

**Issue by pirz** [microsoft/hyperspace#53]
### Describe the issue
Several functions in [`IndexLogManagerImpl`](https://github.com/microsoft/hyperspace/blob/master/src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala)  are using `printStackTrace()` when hitting an unexpected exception.
Change the implementation such that proper Hyperspace logging is used instead of printing the stack.

### To Reproduce
NA

### Expected behavior
[`IndexLogManagerImpl`](https://github.com/microsoft/hyperspace/blob/master/src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala) should not use `printStackTrace()`.
 
### Environment 
NA

**Comment by rapoth** [comment]
CC: sezruby
