### ISSUE TITLE
Add Config file for Hyperspace

### ISSUE THREAD

**Issue by pirz** [microsoft/hyperspace#55]
### Describe the issue
Unify all Hyperspace related configurations in a single configuration file and add them to `spark.conf`.
Check [here](https://microsoft.github.io/hyperspace/docs/ug-configuration) for a list of Hyperspace configurations.

Today, for changing any Hyperspace related config, user needs to manually add it to spark configurations. For example:
`spark.conf.set(IndexConstants.INDEX_SYSTEM_PATH, "some valid path")` 

Ideally, we want these config overrides to be added to a config file, and by enabling Hyperspace they all get added to spark conf automatically (without any action from user side).
 
### To Reproduce
NA

### Expected behavior
A user should be able to add a configuration file and edit it with Hyperspace configurations and the configs should be added automatically to Spark Session.

### Environment 
NA

**Comment by rapoth** [comment]
@pirz Could you clarify what this issue entails?

**Comment by pirz** [comment]
@rapoth I updated the description; plz take a look.

**Comment by rapoth** [comment]
CC: @sezruby

**Comment by sezruby** [comment]
@priz It seems Hyperspace configs from a config file (spark-default.conf or using --properties-file) works well.
Do you think any additional changes are required for the configs such as unit tests or validation of config values?

**Comment by rapoth** [comment]
CC: @imback82 

Thank you for validating this path! If it is already working fine, then I would not expect any other validation.
