### ISSUE TITLE
Add stable state check in IndexLogManager.createLatestStableLog()

### ISSUE THREAD

**Issue by apoorvedave1** [microsoft/hyperspace#56]
### Describe the issue
In   IndexLogManager.createLatestStableLog() make sure the log being copied has a   stable state. The api currently makes a copy of whatever log id it's passed, without 'assert'ing that the state of this log is stable (i.e. ACTIVE, DELETED, DOESNOTEXIST)

### To Reproduce
NA

### Expected behavior
NA
### Environment 
NA

**Comment by saucam** [comment]
Hi,

Let me give this a shot!

**Comment by saucam** [comment]
Here is the PR, please review https://github.com/microsoft/hyperspace/pull/92

**Comment by sezruby** [comment]
@apoorvedave1 I think we can close this issue now. Thanks @saucam!

**Comment by imback82** [comment]
Fixed by #92
