### ISSUE TITLE
Use a clock trait in index cache

### ISSUE THREAD

**Issue by pirz** [microsoft/hyperspace#67]
### Describe the issue
Add clock trait to the code and modify [`CreationTimeBasedIndexCache`](https://github.com/microsoft/hyperspace/blob/master/src/main/scala/com/microsoft/hyperspace/index/CachingIndexCollectionManager.scala) to use the clock with System time by default. Tests cases under [`IndexCacheTest`](https://github.com/microsoft/hyperspace/blob/master/src/test/scala/com/microsoft/hyperspace/index/IndexCacheTest.scala) should be modified to not use `Thread.sleep`.

### To Reproduce
NA

### Expected behavior
`CreationTimeBasedIndexCache` should be modified to use a clock.

`Thread.sleep` usage should be removed from index cache test cases.

**Comment by clee704** [comment]
Is it still open?

**Comment by sezruby** [comment]
closed by #313
