### ISSUE TITLE
Add Python Notebook for Hyperspace

### ISSUE THREAD

**Issue by rapoth** [microsoft/hyperspace#74]
### Describe the issue

Currently, there is only a Scala notebook provided that demonstrates the e2e functionality of Hyperspace. It would be good to have a Python notebook as well.

### To Reproduce

N/A

### Expected behavior

N/A

### Environment 

N/A

**Comment by rapoth** [comment]
CC: @thrajput

**Comment by shril** [comment]
Hi @rapoth, I would like to contribute to this issue.
Can I take this?

**Comment by rapoth** [comment]
Thanks for your interest! Please feel free to take it up, but note that this work depends on #36 (CC: @thrajput) so you might want to wait until that PR gets in (or alternatively, you can feel free to branch off from that PR).

**Comment by shril** [comment]
@rapoth I'll start my work on this issue. And will raise a PR once #36 gets merged in.
I hope that works for you guys?

**Comment by thrajput** [comment]
@shril sounds good. thanks.

**Comment by thrajput** [comment]
@shril python bindings is merged. You can make a PR for python notebook.
