### ISSUE TITLE
Create a sample Hyperspace "HelloWorld" application

### ISSUE THREAD

**Issue by pirz** [microsoft/hyperspace#79]
### Describe the issue
Write a sample Hyperspace `HelloWorld` application code with some simple and reasonable scenario.
Minimally the app code should create some example indexes on some sample data and demonstrate how those indexes can be maintained and used.

Main goal for the app is to show how one can import and use Hyperspace within a Spark application. 

### To Reproduce
NA

### Expected behavior
An example (and ideally configurable) Spark application code which demonstrate core features and capabilities of Hyperspace.

### Environment 
All environments.

**Comment by pherbel** [comment]
Hello, I'm looking forward to it.

Could you share a c# .net spar version too?

**Comment by rapoth** [comment]
CC: @AFFogarty for the C# version

**Comment by AFFogarty** [comment]
Once #90 is completed, I'll open a PR with the C# version.

**Comment by AFFogarty** [comment]
@pirz Should we close this issue now?

**Comment by imback82** [comment]
Closed by #94
